//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryListApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DirectoryEntities : DbContext
    {
        public DirectoryEntities()
            : base("name=DirectoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDirectoryCategory> tblDirectoryCategories { get; set; }
        public virtual DbSet<tblDirectoryDetail> tblDirectoryDetails { get; set; }
        public virtual DbSet<tblDirectoryItem> tblDirectoryItems { get; set; }
        public virtual DbSet<tblDirectorySubCategory> tblDirectorySubCategories { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblPalika> tblPalikas { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
    }
}
