//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryListApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirectorySubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDirectorySubCategory()
        {
            this.tblDirectoryItems = new HashSet<tblDirectoryItem>();
        }
    
        public int DirectorySubCategoryId { get; set; }
        public string DirectorySubCategoryName { get; set; }
        public Nullable<int> DirectoryCategoryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual tblDirectoryCategory tblDirectoryCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDirectoryItem> tblDirectoryItems { get; set; }
    }
}
