//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryListApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int ReviewId { get; set; }
        public Nullable<int> DirectoryItemId { get; set; }
        public string RevFirstName { get; set; }
        public string RevLastName { get; set; }
        public string RevEmail { get; set; }
        public string ReviewDate { get; set; }
        public string Review { get; set; }
        public Nullable<int> ReviewRating { get; set; }
    
        public virtual tblDirectoryItem tblDirectoryItem { get; set; }
    }
}
